version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
    # ports: # <- ПОРТ УДАЛЕН. База данных недоступна снаружи
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: # <- Сервис добавлен в нашу сеть
      - coffeeshop-net

  redis:
    image: redis:7-alpine
    # ports: # <- ПОРТ УДАЛЕН. Redis недоступен снаружи
    #   - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks: # <- Сервис добавлен в нашу сеть
      - coffeeshop-net

  api:
    build: .
    # ports: # <- ПОРТ УДАЛЕН. API будет доступен только через Nginx
    #   - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    networks: # <- Сервис добавлен в нашу сеть
      - coffeeshop-net

  # --- НОВЫЙ СЕРВИС NGINX ---
  nginx:
    image: nginx:1.25-alpine
    ports:
      # Публикуем порт 80 наружу, который будет проксировать запросы на порт 8000 сервиса api
      - "80:80"
    volumes:
      # Подключаем наш конфигурационный файл
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks: # <- Сервис добавлен в нашу сеть
      - coffeeshop-net

  celery_worker:
    build: .
    env_file:
      - .env # <- Лучше использовать env_file для консистентности
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    command: celery -A app.infrastructure.celery.worker worker --loglevel=info
    networks: # <- Сервис добавлен в нашу сеть
      - coffeeshop-net

  celery_beat:
    build: .
    env_file:
      - .env # <- Лучше использовать env_file
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    command: celery -A app.infrastructure.celery.worker beat --loglevel=info
    networks: # <- Сервис добавлен в нашу сеть
      - coffeeshop-net

# --- ОПРЕДЕЛЯЕМ НАШУ ИЗОЛИРОВАННУЮ СЕТЬ ---
networks:
  coffeeshop-net:
    driver: bridge

volumes:
  postgres_data:
